create table if not exists public.responses (
  id bigint generated by default as identity primary key,
  question text not null,
  answer text not null,
  category text not null,
  timestamp timestamptz not null default now(),
  final_status text
);

alter table public.responses enable row level security;

create policy "Anyone may submit a response"
on public.responses for insert
to anon
with check (true);

create policy "Authenticated admin may read responses"
on public.responses for select
to authenticated
using ((auth.jwt() ->> 'email') = 'rahulgosainn@gmail.com');
